# Generated by Django 4.2.4 on 2023-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("delivery_hour", models.TimeField(blank=True, null=True)),
                ("delivery_days", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reminder", models.BooleanField(default=False)),
                ("reminder_in_days", models.IntegerField(blank=True, null=True)),
                ("reminder_deliver_hour", models.TimeField(blank=True, null=True)),
                ("reminder_deliver_days", models.IntegerField(blank=True, max_length=50, null=True)),
                ("reminder_max_tries", models.IntegerField(blank=True, null=True)),
                ("reminder_retry_in_days", models.IntegerField(blank=True, null=True)),
                ("answer_time_limit", models.IntegerField(blank=True, null=True)),
                ("max_valid_operation_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryContentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryInterval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField()),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("hour", "Hora"),
                            ("day", "Día"),
                            ("week", "Semana"),
                            ("month", "Mes"),
                            ("year", "Año"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("send_date", models.DateTimeField(blank=True, null=True)),
                ("start_response_date", models.DateTimeField(blank=True, null=True)),
                ("finish_response_date", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurveyDeliveryConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_available_operation_date", models.DateField(blank=True, null=True)),
                ("delivery_start_date", models.DateField(blank=True, null=True)),
                ("reminder_max_tries", models.IntegerField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("available", "Available")], max_length=20
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.brand")),
                (
                    "incubation_interval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_delivery_incubation_interval",
                        to="delivery.deliveryinterval",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.operationtype",
                    ),
                ),
                (
                    "reminder_interval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_delivery_reminder_interval",
                        to="delivery.deliveryinterval",
                    ),
                ),
                (
                    "response_time_limit_interval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_delivery_response_time_limit_interval",
                        to="delivery.deliveryinterval",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
