# Generated by Django 4.2.4 on 2023-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryconfig",
            name="repeat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryconfig",
            name="repeat_interval_type",
            field=models.CharField(
                blank=True,
                choices=[("", "----"), ("w", "Weeks"), ("m", "Months"), ("y", "Years")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryconfig",
            name="repeat_interval_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryconfig",
            name="delivery_days",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryconfig",
            name="reminder_deliver_days",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
