# Generated by Django 4.2.4 on 2023-10-01 13:44

import dateutil.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_deliveryconfig_repeat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryconfig",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryconfig",
            name="start_date",
            field=models.DateField(blank=True, default=dateutil.utils.today, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryconfig",
            name="repeat_interval_type",
            field=models.CharField(
                blank=True,
                choices=[("", "----"), ("w", "Semanas"), ("m", "Meses"), ("y", "Años")],
                max_length=100,
                null=True,
            ),
        ),
    ]
