# Generated by Django 4.2.4 on 2023-10-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0004_deliveryconfig_end_date_deliveryconfig_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryconfig",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
