# Generated by Django 4.2.4 on 2023-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0006_alter_deliveryconfig_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryconfig",
            name="method",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS"), ("both", "Both")], default="both", max_length=20
            ),
        ),
    ]
