# Generated by Django 4.2.4 on 2023-10-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0007_deliveryconfig_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryconfig",
            name="method",
            field=models.CharField(
                choices=[("both", "Email y SMS"), ("email", "Email"), ("sms", "SMS")], default="both", max_length=20
            ),
        ),
    ]
