default_context:
  _pegasus_version: 2023.9.2
  author_name: Paco
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: heroku_docker
  description: peoplecy_gowit
  docker_setup: default
  domain_name: localhost:8000
  email: pacocastillosa@gmail.com
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: Peoplecy_gowit
  project_slug: peoplecy_gowit
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_keys: n
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_examples: n
  use_impersonation: y
  use_openai: n
  use_sentry: y
  use_subscriptions: n
  use_teams: y
  use_teams_example: n
  use_translations: y
  use_wagtail: n
