# Generated by Django 4.2.4 on 2023-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/logos")),
                ("website", models.URLField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("subsector", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="companies")),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.brand")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="brands", to="companies.company"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="sector",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="companies.sector"
            ),
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.brand")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.component")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
