# Generated by Django 4.2.4 on 2023-10-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0002_customuser_language_customuser_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="brand",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="companies.brand"
            ),
        ),
    ]
