# Generated by Django 4.2.4 on 2023-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadDataFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="files/")),
                ("raw_data", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("client", "Cliente"),
                            ("visit", "Visita"),
                            ("budget", "Presupuesto"),
                            ("purchase", "Compra"),
                            ("payment", "Pago"),
                            ("delivery", "Entrega"),
                            ("issue", "Incidencia"),
                            ("return", "Devolución"),
                            ("order", "Pedido"),
                            ("service", "Servicio"),
                            ("reservation", "Reserva"),
                            ("hire", "Contratación"),
                            ("meal", "Comida"),
                            ("stay", "Estancia"),
                            ("hospitalization", "Hospitalización"),
                            ("claim", "Siniestro"),
                            ("advice", "Asesoramiento"),
                            ("course", "Curso"),
                            ("event", "Evento"),
                            ("client_csv_value_equivalences", "Client Csv Value Equivalences"),
                            ("client_csv_column_equivalences", "Client Csv Column Equivalences"),
                            ("operation_csv_value_equivalences", "Operation Csv Value Equivalences"),
                            ("operation_csv_column_equivalences", "Operation Csv Column Equivalences"),
                        ],
                        max_length=100,
                    ),
                ),
                ("error", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_files",
                        to="companies.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UploadDataFileEventLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error"), ("success", "Success")],
                        max_length=100,
                    ),
                ),
                ("log_event_class", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")], max_length=100
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "uploadDataFile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="upload_data.uploaddatafile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
