# Generated by Django 4.2.4 on 2023-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("id_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_types",
                        to="companies.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationTypeI18n",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        blank=True, choices=[("es", "Español"), ("en", "Inglés")], max_length=10, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="operations.operationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationCsvValueEquivalence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column", models.CharField(max_length=40)),
                ("value", models.CharField(max_length=40)),
                ("equivalence", models.CharField(max_length=100)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.brand")),
                (
                    "operation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_equivalences",
                        to="operations.operationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationCsvColumnEquivalence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column", models.CharField(max_length=40)),
                ("equivalence", models.CharField(max_length=100)),
                ("is_id_value", models.BooleanField(default=False)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.brand")),
                (
                    "operation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_equivalences",
                        to="operations.operationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("internal_id", models.CharField(blank=True, max_length=100, null=True)),
                ("internal_client_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Cliente"),
                            ("visit", "Visita"),
                            ("budget", "Presupuesto"),
                            ("purchase", "Compra"),
                            ("payment", "Pago"),
                            ("delivery", "Entrega"),
                            ("issue", "Incidencia"),
                            ("return", "Devolución"),
                            ("order", "Pedido"),
                            ("service", "Servicio"),
                            ("reservation", "Reserva"),
                            ("hire", "Contratación"),
                            ("meal", "Comida"),
                            ("stay", "Estancia"),
                            ("hospitalization", "Hospitalización"),
                            ("claim", "Siniestro"),
                            ("advice", "Asesoramiento"),
                            ("course", "Curso"),
                            ("event", "Evento"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("operation_status", models.CharField(blank=True, max_length=50, null=True)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("need", models.TextField(blank=True, null=True)),
                ("motivation", models.TextField(blank=True, null=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=50, null=True)),
                ("product", models.CharField(blank=True, max_length=100, null=True)),
                ("professional", models.CharField(blank=True, max_length=50, null=True)),
                ("technician", models.CharField(blank=True, max_length=50, null=True)),
                ("assistant", models.CharField(blank=True, max_length=50, null=True)),
                ("administrative", models.CharField(blank=True, max_length=50, null=True)),
                ("advisor", models.CharField(blank=True, max_length=50, null=True)),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("zone", models.CharField(blank=True, max_length=50, null=True)),
                ("delegation", models.CharField(blank=True, max_length=50, null=True)),
                ("sales_center", models.CharField(blank=True, max_length=50, null=True)),
                ("technical_center", models.CharField(blank=True, max_length=50, null=True)),
                ("channel", models.CharField(blank=True, max_length=50, null=True)),
                ("distributor", models.CharField(blank=True, max_length=50, null=True)),
                ("supplier", models.CharField(blank=True, max_length=50, null=True)),
                ("logistics", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="companies.brand",
                    ),
                ),
                (
                    "linked_operation",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="operations.operation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
