# Generated by Django 4.2.4 on 2023-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_id", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company_name", models.CharField(blank=True, max_length=100, null=True)),
                ("crm_url", models.URLField(blank=True, null=True)),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("contact_notes", models.TextField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("age_range", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("profile", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("importance", models.CharField(blank=True, max_length=20, null=True)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                ("value", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="companies.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
